apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-ingress
  namespace: tenant-acme
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: acme.cppmarkdown.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: conversion-service
                port:
                  number: 80
