apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-service
  labels:
    tenant: {{ .Values.tenant }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: conversion-service
      tenant: {{ .Values.tenant }}
  template:
    metadata:
      labels:
        app: conversion-service
        tenant: {{ .Values.tenant }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: conversion-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
