apiVersion: v1
kind: Service
metadata:
  name: conversion-service
  labels:
    tenant: {{ .Values.tenant }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: conversion-service
    tenant: {{ .Values.tenant }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
